---

- name: Managing Warden client config directory
  file:
    path: "{{ hm_warden_client__config_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Managing Warden client directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ hm_warden_client__daemon_uid | string }}"
    group: "{{ hm_warden_client__daemon_gid | string }}"
    mode: 0755
  with_items:
    - "{{ hm_warden_client__run_path }}"
    - "{{ hm_warden_client__lib_path }}"

- name: Ensure Warden3 utilities are executable
  file:
    path: "{{ item }}"
    mode: 0755
  with_items:
    - /usr/local/bin/warden_filer.py
    - /usr/local/bin/warden_apply.sh

- include: _inc.initfiler.yml
  vars:
    filer_config: "{{ outer_item }}"
  loop: "{{ hm_warden_client__filers }}"
  loop_control:
    loop_var: outer_item


#-------------------------------------------------------------------------------


- name: Configuring Nagios NRPE monitoring
  template:
    src: "{{ item }}"
    dest: /etc/nagios/nrpe.d/warden-client.cfg
    owner: root
    group: root
    mode: 0644
  with_first_found:
    - "inventory/host_files/{{ inventory_hostname }}/honzamach.warden_client/nrpe_warden-client.cfg.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.warden_client/nrpe_warden-client.cfg.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.warden_client/nrpe_warden-client.cfg.j2"
    - "inventory/group_files/servers/honzamach.warden_client/nrpe_warden-client.cfg.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers/honzamach.warden_client/nrpe_warden-client.cfg.j2"
    - "nrpe_warden-client.cfg.{{ ansible_lsb['codename'] }}.j2"
    - "nrpe_warden-client.cfg.j2"
  notify: Restart NRPE service
  when: '"servers_monitored" in group_names'

- name: Configuring system status script
  template:
    src: "{{ item }}"
    dest: /opt/system-status/system-status.d/30-warden-client
    owner: root
    group: root
    mode: 0755
  with_first_found:
    - "inventory/host_files/{{ inventory_hostname }}/honzamach.warden_client/system-status-warden-client.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.warden_client/system-status-warden-client.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.warden_client/system-status-warden-client.j2"
    - "inventory/group_files/servers/honzamach.warden_client/system-status-warden-client.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers/honzamach.warden_client/system-status-warden-client.j2"
    - "system-status-warden-client.{{ ansible_lsb['codename'] }}.j2"
    - "system-status-warden-client.j2"
  when: '"servers_commonenv" in group_names'
