---

- name: Installing necessary packages
  apt:
    name: git
    state: present

- name: Installing Warden from Git repository
  git:
    repo: https://homeproj.cesnet.cz/git/warden.git/
    dest: /opt/warden3
    version: warden-3
    accept_hostkey: yes

- name: Installing Warden service init scripts
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { src: '/opt/warden3/warden3/contrib/warden_filer/warden_filer_receiver', dest: '/etc/init.d/warden_filer_receiver' }
    - { src: '/opt/warden3/warden3/contrib/warden_filer/warden_filer_sender', dest: '/etc/init.d/warden_filer_sender' }

# NOTE: This must be installed with hard copy, otherwise Python does not find the library
- name: Installing Warden3 library and filer and registration utilities into system PATH
  synchronize:
    mode: pull
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    perms: no
  with_items:
    - { src: '/opt/warden3/warden3/warden_client/warden_client.py', dest: '/usr/local/bin/warden_client.py' }
    - { src: '/opt/warden3/warden3/contrib/warden_filer/warden_filer.py', dest: '/usr/local/bin/warden_filer.py' }
    - { src: '/opt/warden3/warden3/contrib/warden_ra/warden_apply.sh', dest: '/usr/local/bin/warden_apply.sh' }
  delegate_to: "{{ inventory_hostname }}"
  notify:
    - Restart Warden receiver service
    - Restart Warden sender service

#
# TODO: Implement task for initial certificate registration using warden-apply.sh
#
